export const FORM_TEXTS = {
    defaultInvalidEmail: "oliver",
    defaultInvalidPhoneNumber: "123",
    defaultEmail: "oliver@example.com",
    defaultFirstName: "Oliver",
    defaultLastName: "Smith",
    defaultPhoneNumber: "9087654321",
    defaultCountryCode: "+1",
    urlParameters: {
        email: "sample@example.com",
        customer_service: 4,
        scale: 7,
        customer_rep: {
            Friendliness: "Excellent",
            Quickness: "Very Good",
            Knowledge: "Average"
        },
        languages: "Ruby,Python",
    },
}

export const CREATE_FORM_TEXTS = {
    optionArray: ["Option 1", "Option 2", "Option 3", "Option 4", "Option 5", "Option 6", "Option 7", "Option 8", "Option 9", "Option 10",],
    singleChoiceQuestionText: "Single - demo field name",
    multipleChoiceQuestionText: "Multiple - demo field name",
    defaultStarRatingQuestion: "Star Rating",
    defaultOpinionScaleQuestion: "Opinion",
    defaultMatrixQuestion: "Matrix",
    defaultFormPassword: "password123",
    standardSingleChoiceQuestionText: "Interested in Playwright?",
    yesOptionText: "Yes",
    noOptionText: "No",
    starRatingQuestionNameText: "Rate customer service",
    opinionScaleQuestionNameText: "Opinion scale",
    matrixQuestionNameText: "Rate Customer Representative",
    starRatingFieldCodeText: "customer_service",
    opinionScaleFieldCodeText: "scale",
    matrixRowTexts: ["Friendliness", "Knowledge", "Quickness"],
    matrixColumnTexts: ["Excellent", "Very Good", "Average"],
    matrixFieldCodeText: "customer_rep",
    multiChoiceQuestionText: "Preferred Language",
    multiChoiceOptionTexts: ["Ruby", "Python", "Javascript", "C"],
    multiChoiceFieldCodeText: "languages",
    themeNameAddString: " theme",
    imageUrl: '/home/samiksha/neetoform-playwright-tests/playwright-tests/e2e/constants/images/my-theme.png',
}