import { LOGIN_SELECTORS, NAVBAR_SELECTORS, CREATE_FORM_PAGE_SELECTORS } from "./createForm";
import { PUBLISHED_FORM_PAGE_SELECTORS, THANK_YOU_PAGE_SELECTORS, FORM_TABLE_SELECTORS } from "./forms";
import { SUBMISSIONS_PAGE_SELECTORS } from "./submissions";

export {
    LOGIN_SELECTORS,
    NAVBAR_SELECTORS,
    CREATE_FORM_PAGE_SELECTORS,
    PUBLISHED_FORM_PAGE_SELECTORS,
    THANK_YOU_PAGE_SELECTORS,
    SUBMISSIONS_PAGE_SELECTORS,
    FORM_TABLE_SELECTORS,
}