import { LOGIN_SELECTORS, NAVBAR_SELECTORS, CREATE_FORM_PAGE_SELECTORS } from "./createForm";
import { PUBLISHED_FORM_PAGE_SELECTORS, THANK_YOU_PAGE_SELECTORS, FORM_TABLE_SELECTORS } from "./forms";
import { SUBMISSIONS_PAGE_SELECTORS } from "./submissions";
import { SETTINGS_PAGE_SELECTORS, ADD_CONDITION_SELECTORS } from "./settings";
import { SHARE_PAGE_SELECTORS } from "./share";
import { THEME_PAGE_SELECTORS } from "./theme";

export {
    LOGIN_SELECTORS,
    NAVBAR_SELECTORS,
    CREATE_FORM_PAGE_SELECTORS,
    PUBLISHED_FORM_PAGE_SELECTORS,
    THANK_YOU_PAGE_SELECTORS,
    SUBMISSIONS_PAGE_SELECTORS,
    FORM_TABLE_SELECTORS,
    SETTINGS_PAGE_SELECTORS,
    SHARE_PAGE_SELECTORS,
    ADD_CONDITION_SELECTORS,
    THEME_PAGE_SELECTORS,
}